### ISSUE TITLE
Error message when email not registered or incorrect password.

### ISSUE THREAD

**Issue by rohinmittal** [ramanpreeet1990/ATMedicine#6]
Same error message thrown. Letting user know if the email is registered but password incorrect OR email not registered would be more informative.

Not urgent.

**Comment by ramanpreetSinghKhinda** [comment]
This is to block any intruder action. Since we are storing user's medical history which need high security and we do not want any 3rd person to crack the system by simple trial and errors. We have used MD5 128 bit encryption to protect user's data against such security attacks. This is one of the security scheme which is being used in industries nowadays where even if the user forgot the password than on entering email id to reset password, the user is not notified whether the entered email id was wrong or correct. Only informative message is displayed like "If your email id exists in the system, than we will send your password"
